from django.db import migrations


UI_CONTENT = {
    "accountDeactivated": "This account has been deactivated. Please contact an administrator.",
    "signinSuccess": "Signin successful",
    "logoutSuccess": "Logged out successfully",
    "adminConnections": "Connections",
    "adminConnectionManagement": "Connection Management",
    "adminConnectionManagementIntro": "Inspect, create, and remove candidate/recruiter relationships.",
    "adminFirstUser": "First User",
    "adminSecondUser": "Second User",
    "adminSelectUser": "Select user",
    "adminCreateConnection": "Create Connection",
    "adminCreatingConnection": "Creating...",
    "adminDisconnect": "Disconnect",
    "adminDisconnecting": "Disconnecting...",
    "adminNoConnections": "No managed connections found.",
    "adminConnectionCreated": "Connection created.",
    "adminConnectionRemoved": "Connection removed.",
    "adminInvalidConnectionUsers": "Choose two different active candidate/recruiter users.",
    "apiAdminConnections": "/connections/admin/connections",
    "apiAdminConnectUsers": "/connections/admin/connect",
    "apiAdminDisconnectUsers": "/connections/admin/disconnect",
    "adminAuditLogs": "Audit Logs",
    "adminAuditLogsIntro": "Review recent admin actions across users and connections.",
    "adminAuditAction": "Action",
    "adminAuditActor": "Actor",
    "adminAuditTarget": "Target",
    "adminAuditTime": "Time",
    "adminNoAuditLogs": "No admin actions have been recorded yet.",
    "apiAdminAuditLogs": "/accounts/admin/audit-logs",
    "emailVerificationSubject": "Verify your Talent Hub email",
    "emailVerificationBody": "Your verification OTP is {otp}. It expires in {minutes} minutes.",
    "emailVerificationSent": "Verification OTP sent. Please check your email.",
    "emailVerificationRequired": "Please verify your email before signing in.",
    "emailVerificationInvalidOtp": "Invalid or expired verification OTP.",
    "emailVerificationTooManyAttempts": "Too many invalid verification attempts. Request a new OTP.",
    "emailVerificationCooldown": "Please wait before requesting another verification OTP.",
    "emailVerificationSuccess": "Email verified. You can now sign in.",
    "emailAlreadyVerified": "Email is already verified.",
    "verifyEmail": "Verify Email",
    "verifyEmailIntro": "Enter the OTP sent to your email to activate your account.",
    "verifyOtp": "Verify OTP",
    "verifyingOtp": "Verifying...",
    "resendOtp": "Resend OTP",
    "resendingOtp": "Resending...",
    "routeVerifyEmail": "/verify-email",
    "apiEmailVerificationRequest": "/accounts/email-verification/request",
    "apiEmailVerificationConfirm": "/accounts/email-verification/confirm",
    "adminPendingRecruiters": "Pending Recruiters",
    "adminRecruiterVerification": "Recruiter Verification",
    "adminRecruiterPending": "Pending",
    "adminRecruiterApproved": "Approved",
    "adminRecruiterRejected": "Rejected",
    "adminApproveRecruiter": "Approve",
    "adminRejectRecruiter": "Reject",
    "adminVerifyingRecruiter": "Updating...",
    "adminRecruiterVerificationInvalidRole": "Only recruiter accounts can be verified.",
    "adminRecruiterVerificationUpdated": "Recruiter verification updated.",
    "recruiterVerificationPendingNotice": "Your recruiter profile is pending admin approval.",
    "recruiterVerificationRejectedNotice": "Your recruiter profile was not approved. Please update your company details or contact support.",
    "apiAdminRecruiterVerificationSuffix": "recruiter-verification",
    "connectionAccept": "Accept",
    "connectionAccepted": "Accepted",
    "connectionAccepting": "Accepting...",
    "connectionAdminUnavailable": "Admin accounts do not use the connections module.",
    "connectionConnect": "Connect",
    "connectionDiscover": "Discover",
    "connectionIgnoring": "Ignoring...",
    "connectionIgnore": "Ignore",
    "connectionIntro": "Manage connection requests and discover professionals.",
    "connectionLoading": "Loading your network...",
    "connectionNoConnections": "You do not have any connections yet.",
    "connectionNoReceivedRequests": "No received requests yet.",
    "connectionNoSearchResults": "No professionals match your search.",
    "connectionNoSentRequests": "No sent requests yet.",
    "connectionReceived": "Received",
    "connectionRequestAccepted": "Connection request accepted.",
    "connectionRequestFailed": "Request failed.",
    "connectionRequestIgnored": "Request ignored.",
    "connectionRequestRejected": "Connection request rejected.",
    "connectionRequestSent": "Connection request sent.",
    "connectionNotFound": "Connection not found.",
    "connectionSearchPlaceholder": "Search by name, email, headline, or location...",
    "connectionSending": "Sending...",
    "connectionSent": "Sent",
    "connectionStatusAccepted": "Accepted",
    "connectionStatusAwaitingResponse": "Awaiting response",
    "connectionStatusConnected": "Connected",
    "connectionStatusDeclined": "Declined",
    "connectionStatusIgnored": "Ignored",
    "connectionStatusNotConnected": "Not connected",
    "connectionStatusPending": "Pending",
    "connectionStatusRequestSent": "Request sent",
    "connectionUnableToLoad": "Unable to load your network right now.",
    "connectionUnableToSend": "Unable to send connection request.",
    "connectionUnableToUpdate": "Unable to update connection request.",
    "viewProfile": "View",
}


def seed_ui_content(apps, schema_editor):
    ui_content = apps.get_model("app_config", "UiContent")

    for key, value in UI_CONTENT.items():
        ui_content.objects.update_or_create(key=key, defaults={"value": value})


class Migration(migrations.Migration):
    dependencies = [
        ("app_config", "0015_seed_connection_ui_content"),
    ]

    operations = [
        migrations.RunPython(seed_ui_content, migrations.RunPython.noop),
    ]
